config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :reviews
  resources :events
  resources :rooms
  resources :users

  root 'home#index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :sessions, only: [:new, :create, :destroy]
  get "up" => "rails/health#show", as: :rails_health_check
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to:"sessions#new", as:'login'
  get 'logout', to:"sessions#destroy",as:'logout'
  get '/users/:id', to:"users#show",as:'profile'
  get 'available_rooms', to: 'rooms#available_rooms',as:"available_rooms"
  get '/:id/my_bookings', to: 'tickets#my_bookings',as:"my_bookings"
  get 'all_bookings', to: 'tickets#all_bookings',as:"all_bookings"
  get '/:id/my_reviews', to: 'reviews#my_reviews',as:"my_reviews"

  # get 'events/search', to: 'events#search', as: 'event_search'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorized, only: [:index]
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%if current_user %>
  <%= link_to "View Events", events_path %> <br>
  <% unless !current_user.is_admin? %>
    <%= link_to "Add Events",new_event_path %> <br>
  <%end %>

  <br>

  <%= link_to "My Reviews", my_reviews_path(id: current_user.id) %> <br>
  <%= link_to "View All Reviews", reviews_path %> <br><br>

  <%= link_to "My Bookings", my_bookings_path(id: current_user.id) %> <br>
  <% unless !current_user.is_admin? %>
    <%= link_to "View All Bookings", all_bookings_path %> <br><br>
  <%end %>

  <% unless !current_user.is_admin? %>
    <%= link_to "Search Attendees by Event", users_path(display: 1) %> <br><br>
  <%end %>

  <% unless !current_user.is_admin? %>
    <%= link_to "View all Attendees", users_path %> <br><br>
  <%end %>

  <% unless !current_user.is_admin? %>
    <%= link_to "View Rooms", rooms_path %> <br>
    <%= link_to "Create Room", new_room_path %><br>
  <%end %>
  <br>
  <%= link_to 'View Profile', profile_path(id: current_user.id) %> <br>
  <%= link_to 'Edit Profile', edit_user_path(id: current_user.id) %><br>
<%else %>
  <%= link_to "Signup", signup_path%> or
  <%= link_to "Login",login_path %>
<%end %>