config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :reviews
  resources :events
  resources :rooms
  resources :users

  root 'home#index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :sessions, only: [:new, :create, :destroy]
  get "up" => "rails/health#show", as: :rails_health_check
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to:"sessions#new", as:'login'
  get 'logout', to:"sessions#destroy",as:'logout'
  get '/users/:id', to:"users#show",as:'profile'
  get 'available_rooms', to: 'rooms#available_rooms',as:"available_rooms"
  get '/:id/my_bookings', to: 'tickets#my_bookings',as:"my_bookings"
  get 'all_bookings', to: 'tickets#all_bookings',as:"all_bookings"
  get '/:id/my_reviews', to: 'reviews#my_reviews',as:"my_reviews"

  # get 'events/search', to: 'events#search', as: 'event_search'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/event.rb
class Event < ApplicationRecord
  validates :event_name, presence: true
  validates :event_category, presence: true
  validates :event_date, presence: true
  validates :event_start_time, presence: true
  validates :event_end_time, presence: true
  validates :ticket_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :number_of_seats_left, presence: true, numericality: { greater_than_or_equal_to: 0 }


  belongs_to :room
  has_many :reviews, dependent: :destroy
  has_many :tickets, dependent: :destroy
  has_many :users
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
    if params[:name].present?
      @events = @events.where('LOWER(event_name) LIKE ?', "%#{params[:name].downcase}%")
    end
    # Filter events based on parameters
    if params[:category].present?
      @events = @events.where(event_category: params[:category])
    end

    if params[:date].present?
      @events = @events.where(event_date: params[:date])
    end

    if params[:minPrice].present?
      min_price = params[:minPrice].to_i
      @events = @events.where('ticket_price >= ?', min_price)
    end

    if params[:maxPrice].present?
      min_price = params[:maxPrice].to_i
      @events = @events.where('ticket_price <= ?', min_price)
    end
    #puts @events[0].event_name
    respond_to do |format|
      format.html # Render HTML view
      format.json { render json: @events } # Render JSON data
    end
  end


  # GET /events/1 or /events/1.json
  def show
    @event = Event.find(params[:id])
    if !current_user.is_admin? && (@event.event_date < Time.now.utc.to_date || (@event.event_date==Time.now.utc.to_date  && @event.event_start_time.strftime('%H:%M') < Time.current.strftime('%H:%M') || @event.number_of_seats_left <= 0))
      redirect_to root_url
    end
  end

  # GET /events/new
  def new
    if !current_user.is_admin?
      redirect_to root_url
    end
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    if !current_user.is_admin?
      redirect_to root_url
    end
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    if !current_user.is_admin?
      redirect_to root_url
    end
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:event_name, :event_category, :event_date, :event_start_time, :event_end_time, :ticket_price, :number_of_seats_left, :room_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Event name:</strong>
    <%= event.event_name %>
  </p>

  <p>
    <strong>Event category:</strong>
    <%= event.event_category %>
  </p>

  <p>
    <strong>Event date:</strong>
    <%= event.event_date %>
  </p>

  <p>
    <strong>Event start time:</strong>
    <%= event.event_start_time %>
  </p>

  <p>
    <strong>Event end time:</strong>
    <%= event.event_end_time %>
  </p>

  <p>
    <strong>Ticket price:</strong>
    <%= event.ticket_price %>
  </p>

  <p>
    <strong>Number of seats left:</strong>
    <%= event.number_of_seats_left %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= event.room_id %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <span style="color: red;"><b>NOTE: To create a future event, make an event post current UTC Time : <%= Time.current%></b></span><br><br>
  <div>
    <%= form.label :event_name, style: "display: block" %>
    <%= form.text_field :event_name %>
  </div>

  <div>
    <%= form.label :event_category, style: "display: block" %>
    <%= form.select :event_category, ['Concert', 'Sport', 'Arts & Theatre', 'Miscellaneous'] %>
  </div>

  <div>
    <%= form.label :event_date, style: "display: block" %>
    <%= form.date_field :event_date, id: "event_date", min: Time.current.utc.to_date%>
  </div>
  <div>
    <%= form.label :event_start_time, style: "display: block" %>
    <%= form.time_field :event_start_time, id: "event_start_time"%>
  </div>

  <div>
    <%= form.label :event_end_time, style: "display: block" %>
    <%= form.time_field :event_end_time, id: "event_end_time" %>
  </div>

  <div>
    <%= form.label :ticket_price, style: "display: block" %>
    <%= form.number_field :ticket_price, step: 'any' %>
  </div>

  <div>
    <%= form.label :number_of_seats_left, style: "display: block" %>
    <%= form.number_field :number_of_seats_left %>
  </div>


  <div>
    <%= form.label :room_id, style: "display: block" %>
    <%= form.select :room_id, [], {}, id: 'room_id' %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>
<script>
    var eventDateField = document.getElementById("event_date");
    var eventStartTimeField = document.getElementById("event_start_time");
    var eventEndTimeField = document.getElementById("event_end_time");
    var roomIDSelect = document.getElementById("room_id");

    // Add event listeners to the form fields
    // Get references to the form fields
    // Function to log event date to the console
    eventDateField.addEventListener("change", logFieldChange);
    eventStartTimeField.addEventListener("change", logFieldChange);
    eventEndTimeField.addEventListener("change", logFieldChange);
    var given_date;
    var given_start_time;
    var given_end_time;
    function logFieldChange(event) {
        var fieldName = event.target.name;
        var fieldValue = event.target.value;
        if (fieldName=="event[event_date]")
            given_date=fieldValue;
        if (fieldName=="event[event_start_time]")
            given_start_time=fieldValue;
        if (fieldName=="event[event_end_time]")
            given_end_time=fieldValue;

        var xhr = new XMLHttpRequest();
        var url = "<%= available_rooms_path %>?date=" + encodeURIComponent(given_date) + "&start_time=" + encodeURIComponent(given_start_time) + "&end_time=" + encodeURIComponent(given_end_time);
        xhr.open("GET", url, true);
        xhr.setRequestHeader("Content-Type", "application/json");
        xhr.onreadystatechange = function() {
            if (xhr.readyState === 4 && xhr.status === 200) {
                var rooms = JSON.parse(xhr.responseText);
                // Clear existing options
                roomIDSelect.innerHTML = "";

                // Add new options based on the events data
                rooms.forEach(function(room) {
                    var option = document.createElement("option");
                    option.text = room.room_location;
                    option.value = room.id;
                    roomIDSelect.add(option);
                });
            }
        };
        xhr.send();
    }

</script>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<style>
    table, td, th {
        border: 1px solid #ddd;
        text-align: left;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        padding: 15px;
    }
</style>
<p style="color: green"><%= notice %></p>
<div style="display: flex; align-items: center;">
  <h1 style="margin-right: 10px;">Events</h1>
  <%if current_user.is_admin? %>
    <%= link_to "New event", new_event_path, class: "btn btn-primary" %>
  <%end %>
</div>

<%= form_tag events_path, method: :get, id: "filterForm" do %>
  <div style="display: flex; align-items: center;">
    <div style="margin-right: 10px;">
      <%= label_tag :name, "Search Name:" %>
      <%= text_field_tag :name, nil, id: "name",value: params[:name] %>

    </div>
    <div style="margin-right: 10px;">
      <%= label_tag :category, "Category:" %>
      <%= select_tag :category, options_for_select([['All', ''], ['Concert', 'Concert'], ['Sport', 'Sport'], ['Arts & Theatre', 'Arts & Theatre'], ['Miscellaneous', 'Miscellaneous']]), id: "category" %>
    </div>

    <div style="margin-right: 10px;">
      <%= label_tag :date, "Date:" %>
      <%= date_field_tag :date, id: "date",value: params[:date] %>
    </div>

    <div style="margin-right: 10px;">
      <%= label_tag :minPrice, "Min Price:" %>
      <%= number_field_tag :minPrice, id: "minPrice", value: params[:minPrice]%>
    </div>

    <div style="margin-right: 10px;">
      <%= label_tag :maxPrice, "Max Price:" %>
      <%= number_field_tag :maxPrice, id: "maxPrice",value: params[:maxPrice] %>
    </div>
    <%= submit_tag "Filter" %>
  </div>
<% end %>
<%= link_to 'Clear Filter', events_path, class: 'btn btn-secondary' %><br><br>
<div id="events">
  <table>
    <thead>
    <tr>
      <th>Event Name</th>
      <th>Event Category</th>
      <th>Event Date</th>
      <th>Event Start Time</th>
      <th>Event End Time</th>
      <th>Ticket Price</th>
      <th>Seats Left</th>
      <th>Room</th>
      <!-- Add more table headers as needed -->
    </tr>
    </thead>
    <tbody>
    <% @events.each do |event| %>
      <% if current_user.is_admin %>

        <tr>
          <td><%= event.event_name %></td>
          <td><%= event.event_category %></td>
          <td><%= event.event_date%></td>
          <td><%= event.event_start_time.strftime('%H:%M') %></td>
          <td><%= event.event_end_time.strftime('%H:%M') %></td>
          <td><%= event.ticket_price %></td>
          <td><%= event.number_of_seats_left %></td>
          <td><%= Room.find(event.room_id).room_location%></td>
          <td colspan="2">
            <%= link_to "Show", event %>
          </td>

      <% else %>
        <% event_date = event.event_date %>
        <% current_date = Time.current.utc.to_date  %>
        <% event_time = event.event_start_time.strftime("%H:%M") %>
        <% current_time = Time.current.strftime("%H:%M") %>
        <% if (event.number_of_seats_left > 0) && ((event_date > current_date) || (event_date == current_date && event_time > current_time)) %>
          <tr>
            <td><%= event.event_name %></td>
            <td><%= event.event_category %></td>
            <td><%= event.event_date.strftime('%Y-%m-%d') %></td>
            <td><%= event.event_start_time.strftime('%H:%M') %></td>
            <td><%= event.event_end_time.strftime('%H:%M') %></td>
            <td><%= event.ticket_price %></td>
            <td><%= event.number_of_seats_left %></td>
            <td><%= Room.find(event.room_id).room_location%></td>
            <td colspan="2">
              <%= link_to "Show", event %>
            </td>
          </tr>
        <% else %>

        <% end %>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        document.getElementById("filterForm").addEventListener("submit", function(event) {
            event.preventDefault(); // Prevent default form submission
            // Collect filter criteria
            var category = document.getElementById("category").value;
            var date = document.getElementById("date").value;
            var minPrice = document.getElementById("minPrice").value;
            var maxPrice = document.getElementById("maxPrice").value;
            var name = document.getElementById("name").value;

            // Send AJAX request to fetch filtered events
            var xhr = new XMLHttpRequest();
            var url = "<%= events_path %>?category=" + encodeURIComponent(category) + "&date=" + encodeURIComponent(date) + "&min_price=" + encodeURIComponent(minPrice) + "&max_price=" + encodeURIComponent(maxPrice)+ "&name=" + encodeURIComponent(name);
            xhr.open("GET", url, true);
            xhr.setRequestHeader("Accept", "application/json");
            xhr.onreadystatechange = function() {
                if (xhr.readyState === 4 && xhr.status === 200) {
                    var events = JSON.parse(xhr.responseText);
                    var eventsHTML = "<table>" +
                      "<thead>" +
                      "<tr>" +
                      "<th>Event Name</th>" +
                      "<th>Event Category</th>" +
                      "<th>Event Date</th>" +
                      "<th>Event Start Time</th>" +
                      "<th>Event End Time</th>" +
                      "<th>Ticket Price</th>" +
                      "<th>Seats Left</th>" +
                      "<th>Room</th>" +
                      "<!-- Add more table headers as needed -->" +
                      "</tr>" +
                      "</thead>" +
                      "<tbody>";

                    events.forEach(function(event) {
                        if (current_user.is_admin)
                        {
                            var eventHTML = "<tr>" +
                              "<td>" + event.event_name + "</td>" +
                              "<td>" + event.event_date + "</td>" +
                              "<td>" + event.event_category + "</td>" +
                              "<td>" + event.event_start_time + "</td>" +
                              "<td>" + event.event_end_time + "</td>" +
                              "<td>" + event.ticket_price + "</td>" +
                              "<td>" + event.number_of_seats_left + "</td>" +
                              "<td>" + Room.find(event.room_id).room_location + "</td>" +
                              "<td colspan='2'>" +
                              "<a href='/events/" + event.id + "'>Show this event</a>" +
                              "</td>" +
                              "</tr>";
                        }
                        else
                        {
                            var event_date = event.event_date;
                            var current_date = Time.current.utc.to_date
                            var event_time = event.event_start_time.strftime("%H:%M")
                            var current_time = Time.current.strftime("%H:%M")
                            if((event.number_of_seats_left > 0) && ((event_date > current_date) || (event_date == current_date && event_time > current_time)))
                            {
                                var eventHTML = "<tr>" +
                                  "<td>" + event.event_name + "</td>" +
                                  "<td>" + event.event_date + "</td>" +
                                  "<td>" + event.event_category + "</td>" +
                                  "<td>" + event.event_start_time + "</td>" +
                                  "<td>" + event.event_end_time + "</td>" +
                                  "<td>" + event.ticket_price + "</td>" +
                                  "<td>" + event.number_of_seats_left + "</td>" +
                                  "<td>" + Room.find(event.room_id).room_location + "</td>" +
                                  "<td colspan='2'>" +
                                  "<a href='/events/" + event.id + "'>Show this event</a>" +
                                  "</td>" +
                                  "</tr>";
                            }
                            else
                            {}
                        }

                        eventsHTML += eventHTML;
                    });

                    eventsHTML += "</tbody>" +
                      "</table>";

                    document.getElementById("events").innerHTML = eventsHTML;
                }
            };
            xhr.send();

        });
    });
</script>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <p><strong>Event Name:</strong> <%= @event.event_name %></p>
  <p><strong>Event Category:</strong> <%= @event.event_category %></p>
  <p><strong>Event Date:</strong> <%= @event.event_date %></p>
  <p><strong>Event Start Time:</strong> <%= @event.event_start_time.strftime('%H:%M') %></p>
  <p><strong>Event End Time:</strong> <%= @event.event_end_time.strftime('%H:%M')  %></p>
  <p><strong>Ticket Price:</strong> <%= @event.ticket_price %></p>
  <p><strong>Number of Seats Left:</strong> <%= @event.number_of_seats_left %></p>
  <p><strong>Room:</strong> <%= Room.find_by_id(@event.room_id).room_location %></p>
</div>


<div>
  <% unless @event.event_date < Time.current.utc.to_date  || (@event.event_date == Time.current.utc.to_date  && @event.event_start_time.strftime("%H:%M") <= Time.current.strftime("%H:%M") )|| @event.number_of_seats_left <= 0 %>
  <%= link_to "Book tickets", new_ticket_path(event_id: @event.id, user_id: current_user.id, room_id: @event.room.id,belongs_to: current_user.id) %>
    <%= link_to "Book for others", new_ticket_path(event_id: @event.id, room_id: @event.room.id) %>
<%end %>
  <br><br>
  <div class="d-flex justify-content-between">
    <% unless !current_user.is_admin? %>
      <%= link_to "Edit this event", edit_event_path(@event) %> |
    <% end %>
    <%= link_to "Back to events", events_path %>
    <% unless !current_user.is_admin? %>
    <% end %>
  </div>

  <%= button_to "Destroy this event", @event, method: :delete %>

</div>