config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :reviews
  resources :events
  resources :rooms
  resources :users

  root 'home#index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :sessions, only: [:new, :create, :destroy]
  get "up" => "rails/health#show", as: :rails_health_check
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to:"sessions#new", as:'login'
  get 'logout', to:"sessions#destroy",as:'logout'
  get '/users/:id', to:"users#show",as:'profile'
  get 'available_rooms', to: 'rooms#available_rooms',as:"available_rooms"
  get '/:id/my_bookings', to: 'tickets#my_bookings',as:"my_bookings"
  get 'all_bookings', to: 'tickets#all_bookings',as:"all_bookings"
  get '/:id/my_reviews', to: 'reviews#my_reviews',as:"my_reviews"

  # get 'events/search', to: 'events#search', as: 'event_search'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  validates :number_of_tickets, presence: true
  validates :confirmation_number, presence: true, numericality: { greater_than_or_equal_to: 1 }

  belongs_to :room
  belongs_to :event
  belongs_to :user
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    if current_user.id != params[:id].to_i
      redirect_to root_url
    else
      @tickets = current_user.tickets
    end
  end

  def my_bookings
    if current_user.id != params[:id].to_i
      redirect_to root_url
    else
      @tickets = Ticket.where("user_id = ? OR belongs_to = ?", current_user.id, current_user.id)
      if params[:event_name_search].present?
        # Use the SQL LIKE operator to find email IDs similar to the search term
        search_term = "%#{params[:event_name_search]}%"
        @events = Event.where('event_name LIKE ?', search_term)
        # Get IDs of matching users
        event_ids = @events.pluck(:id)
        # Filter reviews by user IDs
        @tickets = @tickets.where(event_id: event_ids)
      end
      render :index # Reuse the index view
    end
  end

  def all_bookings
    if !current_user.is_admin?
      redirect_to root_url
    else
      @tickets = Ticket.all
      if params[:event_name_search].present?
        # Use the SQL LIKE operator to find email IDs similar to the search term
        search_term = "%#{params[:event_name_search]}%"
        @events = Event.where('event_name LIKE ?', search_term)
        # Get IDs of matching users
        event_ids = @events.pluck(:id)
        # Filter reviews by user IDs
        @tickets = @tickets.where(event_id: event_ids)
      end
      if params[:user_name_search].present?
        user_search_term = "%#{params[:user_name_search]}%"
        @users = User.where('name LIKE ?', user_search_term)
        user_ids = @users.pluck(:id)

        # Filter reviews by event IDs
        @tickets = @tickets.where("user_id IN (?) OR belongs_to IN (?)", user_ids, user_ids)
      end
      render :index
    end
  end


  # GET /tickets/1 or /tickets/1.json
  def show
    if !current_user.is_admin? && (current_user.id!=@ticket.user_id && current_user.id != @ticket.belongs_to)
      redirect_to root_url
    end
  end

  # GET /tickets/new
  def new
    @event = Event.find(params[:event_id])
    if (@event.number_of_seats_left<=0 || @event.event_date < Time.current.utc.to_date || (@event.event_date == Time.current.utc.to_date && @event.event_start_time.strftime("%H:%M") < Time.current.strftime("%H:%M")))
      redirect_to root_url
    else
      @event = Event.find(params[:event_id])
      @confirmation_number = SecureRandom.random_number(1_000..9_999)
      @room = Room.find_by_id(@event.room_id)
      @ticket = Ticket.new
      if !params[:user_id].present?
        @users=User.all
        render :other
      end
    end



  end

  # GET /tickets/1/edit
  def edit
    redirect_to root_url
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @event = Event.find(params[:ticket][:event_id])
    @ticket.update(confirmation_number: generate_confirmation_number)
    if params[:ticket][:user_email_search].present?
      @other_user = User.find_by(email:params[:ticket][:user_email_search])
      @ticket.update(belongs_to: @other_user.id)
    end
    respond_to do |format|
      if @ticket.save
        @event.update(number_of_seats_left: @event.number_of_seats_left - @ticket.number_of_tickets)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @event = Event.find_by_id(@ticket.event_id)
    @event.update(number_of_seats_left: @event.number_of_seats_left + @ticket.number_of_tickets)
    @ticket.destroy!
    respond_to do |format|
      format.html { redirect_to my_bookings_path, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:confirmation_number, :room_id, :event_id, :user_id, :number_of_tickets, :belongs_to)
    end
    def generate_confirmation_number
      rand(100_000..999_999)
    end

end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :confirmation_number, style: "display: block" %>
    <%= form.text_field :confirmation_number, readonly:true %>
  </div>

  <div>
    <%= form.label :room_id, style: "display: block" %>
    <%= form.text_field :room_id, readonly:true %>
  </div>

  <div>
    <%= form.label :event_id, style: "display: block" %>
    <%= form.text_field :event_id, readonly:true %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id, readonly:true %>
  </div>

  <div>
    <%= form.label :number_of_tickets, style: "display: block" %>
    <%= form.number_field :number_of_tickets %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/_ticket.html.erb
<div id="<%= dom_id ticket %>">
  <p>
    <strong>Confirmation number:</strong>
    <%= ticket.confirmation_number %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= ticket.room.room_location %>
  </p>

  <p>
    <strong>Event:</strong>
    <%= ticket.event.event_name %>
  </p>

  <p>
    <strong>Booked By:</strong>
    <%= ticket.user.name %>
  </p>
  <p>
    <strong>Belongs to:</strong>
    <%if !User.find_by_id(ticket.belongs_to).nil? %>
      <%= User.find_by_id(ticket.belongs_to).name %>
      <%else %>
      NIL
    <%end %>
  </p>
  <p>
    <strong>Number of Tickets:</strong>
    <%= ticket.number_of_tickets %>
  </p>

  <% event = Event.find(ticket.event_id) %>
  <% total_price = event.ticket_price * ticket.number_of_tickets %>
  <p>
    <strong>Total Price:</strong>
    <%= number_to_currency(total_price) %>
  </p>

</div>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Show this ticket", @ticket %> |
  <%= link_to "Back to tickets", tickets_path %>
</div>

app/views/tickets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tickets</h1>
<% if controller.action_name == 'all_bookings' %>
  <%= form_with(url: all_bookings_path, method: :get) do |form| %>
    <div class="form-group">
      <%= form.label :event_name, "Filter by event:" %>
      <%= form.text_field :event_name_search, placeholder: 'Search by event name', class: 'form-control', id: 'event_name_search', value: params[:event_name_search]%>
    </div>
    <div class="form-group">
      <%= form.label :user_name, "Filter by user:" %>
      <%= form.text_field :user_name_search, placeholder: 'Search by user name', class: 'form-control', id: 'user_name_search', value: params[:user_name_search] %>

    </div>
    <%= form.submit 'Filter', class: 'btn btn-primary' %>
  <% end %>
  <%= link_to 'Clear Filter', all_bookings_path, class: 'btn btn-secondary' %>
<% end %>

<% if controller.action_name == 'my_bookings' %>
  <%= form_with(url: my_bookings_path, method: :get) do |form| %>
    <div class="form-group">
      <%= form.label :event_name, "Filter by event:" %>
      <%= form.text_field :event_name_search, placeholder: 'Search by event name', class: 'form-control', id: 'event_name_search', value: params[:event_name_search]%>
    </div>
    <%= form.submit 'Filter', class: 'btn btn-primary' %>
  <% end %>
  <%= link_to 'Clear Filter', my_bookings_path, class: 'btn btn-secondary' %>
<% end %>

<div id="tickets">
  <% @tickets.each do |ticket| %>
    <%= render ticket %>
    <%event_time = ticket.event.event_end_time.strftime("%H:%M") %>
    <%current_time = Time.current.strftime("%H:%M") %>
    <% if (ticket.user_id == current_user.id || ticket.belongs_to == current_user.id) && (ticket.event.event_date < Time.current.utc.to_date || (ticket.event.event_date == Time.current.utc.to_date && event_time < current_time)) && ticket.event.event_category != 'Miscellaneous'%>
<p>
        <%= link_to "Write a review", new_review_path(event_id: ticket.event_id, user_id: current_user.id) %>
      </p>
    <% end %>
      <%= link_to "Show this ticket", ticket %>
    </p>
  <% end %>
</div>

app/views/tickets/new.html.erb
<%= form_with(model: @ticket, url: tickets_path, local: true) do |form| %>
  <div class="field">
    <strong>Event:</strong> <%= @event.event_name %>
    <%= form.hidden_field :event_id, value: @event.id %>
  </div>
  <div class="field">
    <strong>Booked By:</strong> <%= current_user.name %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="field">
    <strong>Belongs To:</strong> <%= current_user.name %>
    <%= form.hidden_field :belongs_to, value: current_user.id %>
  </div>
  <div class="field">
    <strong>Room:</strong> <%= @room.room_location %>
    <%= form.hidden_field :room_id, value: @room.id %>
  </div>
  <div class="field">
    <strong>Credit Card:</strong> <%= current_user.credit_card_information %>
  </div>
  <div class="field">
    <strong>Price per Ticket:</strong> <%= number_to_currency(@event.ticket_price) %>
  </div>
  <div class="field">
    <% qty = @event.number_of_seats_left %>
    <%= form.label :quantity %>
    <%= form.number_field :number_of_tickets, value: 1, :id => 'quantity',min: 1, max: qty, onchange: "calculateTotalPrice();" %>
  </div>
  <div class="field">
    <%= form.label :total_price %>
    <%= form.text_field :total_price, value: @event.ticket_price,:id => 'total_price', :readonly => true %>
  </div>
  <div class="actions">
    <%= form.submit "Purchase Tickets" %>
  </div>
<% end %>

<script type="text/javascript">
    function calculateTotalPrice() {
        var price = "<%= @event.ticket_price %>";
        document.getElementById('total_price').value = document.getElementById('quantity').value * price;
    }
</script>

app/views/tickets/other.html.erb
<%= form_with(model: @ticket, url: tickets_path, local: true) do |form| %>
  <div id="users-data" data-users="<%= User.all.to_json %>"></div>

  <div class="form-group">
    <%= form.label :user_email_search, "Enter email id:" %>
    <%= form.text_field :user_email_search, id: 'user_email_search', value: params[:user_email_search], onchange: 'handleEmailSearch()'%>
  </div>
  <div class="field">
    <strong>Event:</strong> <%= @event.event_name %>
    <%= form.hidden_field :event_id, value: @event.id %>
  </div>
  <div class="field">
    <strong>Booked By:</strong> <%= current_user.name %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="field">
    <strong>Room:</strong> <%= @room.room_location %>
    <%= form.hidden_field :room_id, value: @room.id %>
  </div>
  <div class="field">
    <strong>Credit Card:</strong> <%= current_user.credit_card_information %>
  </div>
  <div class="field">
    <strong>Price per Ticket:</strong> <%= number_to_currency(@event.ticket_price) %>
  </div>
  <div class="field">
    <% qty = @event.number_of_seats_left %>
    <%= form.label :quantity %>
    <%= form.number_field :number_of_tickets, value: 1, :id => 'quantity',min: 1, max: qty, onchange: "calculateTotalPrice();" %>
  </div>
  <div class="field">
    <%= form.label :total_price %>
    <%= form.text_field :total_price, value: @event.ticket_price,:id => 'total_price', :readonly => true %>
  </div>
  <div class="actions">
    <%= form.submit "Purchase Tickets", id:"submit_button" %>
  </div>
<% end %>

<script type="text/javascript">
    function calculateTotalPrice() {
        var price = "<%= @event.ticket_price %>";
        document.getElementById('total_price').value = document.getElementById('quantity').value * price;
    }
</script>


<script>
    function handleEmailSearch() {

        const userEmailSearchInput = document.getElementById('user_email_search');
        const enteredValue = userEmailSearchInput.value;
        const usersDataDiv = document.getElementById('users-data');
        const allUsers = JSON.parse(usersDataDiv.getAttribute('data-users'));
        console.log('All Users:', allUsers);
        const userFound = allUsers.some(user => user.email === enteredValue);
        if (!userFound) {
            alert('User with entered email not found');
            document.getElementById('submit_button').disabled = true;
        }
        else
        {
            document.getElementById('submit_button').disabled = false;
        }
    }
</script>

app/views/tickets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ticket %>

<div>
  <%= link_to "Show all my tickets", my_bookings_path(id: current_user.id) %>
  <%if current_user.id == @ticket.user_id %>
    <%= button_to "Delete this ticket", @ticket, method: :delete %>
  <%end %>
</div>